### ISSUE TITLE
No support for filtering data by creation date

### ISSUE THREAD

**Issue by nsbraksa** [benhadinehoussam/Starred_Github_repos-Reactjs#1]
The current URL structure doesn't seem like it enables filtering the response data by `creation` date nor `sort` nor `order`. Would love to hear your thoughts on that. 

https://github.com/benhadinehoussam/Starred_Github_repos-Reactjs/blob/45a66d038a8f8e6a5f34242a4940b9454e5204d4/src/services/GitHubAPI.js#L5

**Comment by benhadinehoussam** [comment]
Hey Zack,

First I'm sorry for the late reply, just finished some academic tasks

Indeed I forgot to add some sorting on the data, I'm thinking of two
possibilities

The first one that came to my mind is using Array.sort() ,a native
JavaScript  function, I think it will work seen that we can compare dates
by subtraction, we may need also to use moment.js that allows comparing and
formatting dates.

The second is to use a library called loadash, we can use the orderBy
function, it takes 3 arguments, collection(Array, Object), the element we
want to sort by (Array[], Function[],string..) and the sorting order
(['asc'], ['desc']), it returns the sorted array.

I think the first one will only be comparing dates, days but not times and
minutes. There are many sorting algorithms to sort values, and JavaScript
has many ways to do the sorting.


Le lun. 13 janv. 2020 à 16:31, Zack Braksa <notifications@github.com> a
écrit :
